# Generated by Django 5.0.7 on 2024-07-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('shelter_name', models.CharField(max_length=255)),
                ('animal_type', models.CharField(max_length=255)),
                ('pet_name', models.CharField(max_length=255)),
                ('breed', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.URLField(blank=True, null=True)),
                ('gender', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('size', models.CharField(max_length=255)),
                ('shelter_duration', models.CharField(max_length=255)),
                ('medical_conditions', models.TextField(blank=True, null=True)),
                ('vaccines', models.TextField(blank=True, null=True)),
                ('character', models.TextField(blank=True, null=True)),
                ('behavior', models.TextField(blank=True, null=True)),
                ('commands', models.TextField(blank=True, null=True)),
                ('relation_to_people', models.TextField(blank=True, null=True)),
                ('relation_to_animals', models.TextField(blank=True, null=True)),
                ('availability', models.CharField(max_length=255)),
            ],
        ),
    ]
